# yaml-language-server: $schema=https://aka.ms/ai-foundry-vsc/agent/1.0.0
version: 1.0.0
name: openapi agent
description: Description of the agent
id: 
metadata:
  authors:
    - author1
    - author2
  tags:
    - tag1
    - tag2
model:
  id: gpt-4o
  options:
    temperature: 1
    top_p: 1
instructions: Instructions for the agent
tools:
  - type: openapi
    id: GetCurrentWeather
    description: Retrieves current weather data for a location based on wttr.in.
    options:
      specification: |
        {
          "openapi": "3.1.0",
          "info": {
            "title": "Get Weather Data",
            "description": "Retrieves current weather data for a location based on wttr.in.",
            "version": "v1.0.0"
          },
          "servers": [
            {
              "url": "https://wttr.in"
            }
          ],
          "auth": [],
          "paths": {
            "/{location}": {
              "get": {
                "description": "Get weather information for a specific location",
                "operationId": "GetCurrentWeather",
                "parameters": [
                  {
                    "name": "location",
                    "in": "path",
                    "description": "City or location to retrieve the weather for",
                    "required": true,
                    "schema": {
                      "type": "string"
                    }
                  },
                  {
                    "name": "format",
                    "in": "query",
                    "description": "Always use j1 value for this parameter",
                    "required": true,
                    "schema": {
                      "type": "string",
                      "default": "j1"
                    }
                  }
                ],
                "responses": {
                  "200": {
                    "description": "Successful response",
                    "content": {
                      "text/plain": {
                        "schema": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "404": {
                    "description": "Location not found"
                  }
                },
                "deprecated": false
              }
            }
          },
          "components": {
            "schemes": {}
          }
        }
      auth:
        type: anonymous
